# syntax=docker/dockerfile:1.7-labs

FROM alpine:3.20
RUN apk add --no-cache docker-cli bash

COPY scripts/deploy/installer-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
