version: "3.8"

networks:
  vlab-network:
    driver: overlay
    attachable: true

services:
  manager:
    image: ghcr.io/nunu27/vlab-bun-manager:latest
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MANAGER_ID={{.Node.ID}}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - vlab-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

  worker:
    image: ghcr.io/nunu27/vlab-bun-worker:latest
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - WORKER_ID={{.Node.ID}}
      - MANAGER_GRPC_URL=http://manager:50051
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - vlab-network
    deploy:
      mode: global
      restart_policy:
        condition: any

  guacd:
    image: linuxserver/guacd:latest
    networks:
      - vlab-network
    deploy:
      mode: global
      restart_policy:
        condition: any
      labels:
        - "app.vlab.component=guacd"
