// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: monitor.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "vlab.monitor";

export interface MonitorEvent {
	/** A JSON payload representing the event from clab-monitor */
	type: string;
	payload: string;
}

function createBaseMonitorEvent(): MonitorEvent {
	return { type: "", payload: "" };
}

export const MonitorEvent: MessageFns<MonitorEvent> = {
	encode(
		message: MonitorEvent,
		writer: BinaryWriter = new BinaryWriter(),
	): BinaryWriter {
		if (message.type !== "") {
			writer.uint32(10).string(message.type);
		}
		if (message.payload !== "") {
			writer.uint32(18).string(message.payload);
		}
		return writer;
	},

	decode(input: BinaryReader | Uint8Array, length?: number): MonitorEvent {
		const reader =
			input instanceof BinaryReader ? input : new BinaryReader(input);
		const end = length === undefined ? reader.len : reader.pos + length;
		const message = createBaseMonitorEvent();
		while (reader.pos < end) {
			const tag = reader.uint32();
			switch (tag >>> 3) {
				case 1: {
					if (tag !== 10) {
						break;
					}

					message.type = reader.string();
					continue;
				}
				case 2: {
					if (tag !== 18) {
						break;
					}

					message.payload = reader.string();
					continue;
				}
			}
			if ((tag & 7) === 4 || tag === 0) {
				break;
			}
			reader.skip(tag & 7);
		}
		return message;
	},

	fromJSON(object: any): MonitorEvent {
		return {
			type: isSet(object.type) ? globalThis.String(object.type) : "",
			payload: isSet(object.payload) ? globalThis.String(object.payload) : "",
		};
	},

	toJSON(message: MonitorEvent): unknown {
		const obj: any = {};
		if (message.type !== "") {
			obj.type = message.type;
		}
		if (message.payload !== "") {
			obj.payload = message.payload;
		}
		return obj;
	},

	create(base?: DeepPartial<MonitorEvent>): MonitorEvent {
		return MonitorEvent.fromPartial(base ?? {});
	},
	fromPartial(object: DeepPartial<MonitorEvent>): MonitorEvent {
		const message = createBaseMonitorEvent();
		message.type = object.type ?? "";
		message.payload = object.payload ?? "";
		return message;
	},
};

export type MonitorServiceDefinition = typeof MonitorServiceDefinition;
export const MonitorServiceDefinition = {
	name: "MonitorService",
	fullName: "vlab.monitor.MonitorService",
	methods: {
		streamMonitorEvents: {
			name: "StreamMonitorEvents",
			requestType: MonitorEvent as typeof MonitorEvent,
			requestStream: true,
			responseType: Empty as typeof Empty,
			responseStream: false,
			options: {},
		},
	},
} as const;

export interface MonitorServiceImplementation<CallContextExt = {}> {
	streamMonitorEvents(
		request: AsyncIterable<MonitorEvent>,
		context: CallContext & CallContextExt,
	): Promise<DeepPartial<Empty>>;
}

export interface MonitorServiceClient<CallOptionsExt = {}> {
	streamMonitorEvents(
		request: AsyncIterable<DeepPartial<MonitorEvent>>,
		options?: CallOptions & CallOptionsExt,
	): Promise<Empty>;
}

type Builtin =
	| Date
	| Function
	| Uint8Array
	| string
	| number
	| boolean
	| undefined;

export type DeepPartial<T> = T extends Builtin
	? T
	: T extends globalThis.Array<infer U>
		? globalThis.Array<DeepPartial<U>>
		: T extends ReadonlyArray<infer U>
			? ReadonlyArray<DeepPartial<U>>
			: T extends {}
				? { [K in keyof T]?: DeepPartial<T[K]> }
				: Partial<T>;

function isSet(value: any): boolean {
	return value !== null && value !== undefined;
}

export interface MessageFns<T> {
	encode(message: T, writer?: BinaryWriter): BinaryWriter;
	decode(input: BinaryReader | Uint8Array, length?: number): T;
	fromJSON(object: any): T;
	toJSON(message: T): unknown;
	create(base?: DeepPartial<T>): T;
	fromPartial(object: DeepPartial<T>): T;
}
