// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: worker.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "vlab.worker";

export interface WorkerSpec {
	cpuCores: number;
	memoryMb: number;
	storageMb: number;
}

export interface CommandPayload {
	workerSpec?: WorkerSpec | undefined;
	rpcMessage?: Uint8Array | undefined;
}

export interface CommandRequest {
	rpcMessage: Uint8Array;
}

export interface MetricsRequest {
	cpuUsagePercent: number;
	memoryUsagePercent: number;
	storageUsagePercent: number;
	score: number;
	activeLabs: number;
	activeNodes: number;
}

export interface MetricsResponse {
	success: boolean;
}

function createBaseWorkerSpec(): WorkerSpec {
	return { cpuCores: 0, memoryMb: 0, storageMb: 0 };
}

export const WorkerSpec: MessageFns<WorkerSpec> = {
	encode(
		message: WorkerSpec,
		writer: BinaryWriter = new BinaryWriter(),
	): BinaryWriter {
		if (message.cpuCores !== 0) {
			writer.uint32(8).int32(message.cpuCores);
		}
		if (message.memoryMb !== 0) {
			writer.uint32(16).int32(message.memoryMb);
		}
		if (message.storageMb !== 0) {
			writer.uint32(24).int32(message.storageMb);
		}
		return writer;
	},

	decode(input: BinaryReader | Uint8Array, length?: number): WorkerSpec {
		const reader =
			input instanceof BinaryReader ? input : new BinaryReader(input);
		const end = length === undefined ? reader.len : reader.pos + length;
		const message = createBaseWorkerSpec();
		while (reader.pos < end) {
			const tag = reader.uint32();
			switch (tag >>> 3) {
				case 1: {
					if (tag !== 8) {
						break;
					}

					message.cpuCores = reader.int32();
					continue;
				}
				case 2: {
					if (tag !== 16) {
						break;
					}

					message.memoryMb = reader.int32();
					continue;
				}
				case 3: {
					if (tag !== 24) {
						break;
					}

					message.storageMb = reader.int32();
					continue;
				}
			}
			if ((tag & 7) === 4 || tag === 0) {
				break;
			}
			reader.skip(tag & 7);
		}
		return message;
	},

	fromJSON(object: any): WorkerSpec {
		return {
			cpuCores: isSet(object.cpuCores)
				? globalThis.Number(object.cpuCores)
				: isSet(object.cpu_cores)
					? globalThis.Number(object.cpu_cores)
					: 0,
			memoryMb: isSet(object.memoryMb)
				? globalThis.Number(object.memoryMb)
				: isSet(object.memory_mb)
					? globalThis.Number(object.memory_mb)
					: 0,
			storageMb: isSet(object.storageMb)
				? globalThis.Number(object.storageMb)
				: isSet(object.storage_mb)
					? globalThis.Number(object.storage_mb)
					: 0,
		};
	},

	toJSON(message: WorkerSpec): unknown {
		const obj: any = {};
		if (message.cpuCores !== 0) {
			obj.cpuCores = Math.round(message.cpuCores);
		}
		if (message.memoryMb !== 0) {
			obj.memoryMb = Math.round(message.memoryMb);
		}
		if (message.storageMb !== 0) {
			obj.storageMb = Math.round(message.storageMb);
		}
		return obj;
	},

	create(base?: DeepPartial<WorkerSpec>): WorkerSpec {
		return WorkerSpec.fromPartial(base ?? {});
	},
	fromPartial(object: DeepPartial<WorkerSpec>): WorkerSpec {
		const message = createBaseWorkerSpec();
		message.cpuCores = object.cpuCores ?? 0;
		message.memoryMb = object.memoryMb ?? 0;
		message.storageMb = object.storageMb ?? 0;
		return message;
	},
};

function createBaseCommandPayload(): CommandPayload {
	return { workerSpec: undefined, rpcMessage: undefined };
}

export const CommandPayload: MessageFns<CommandPayload> = {
	encode(
		message: CommandPayload,
		writer: BinaryWriter = new BinaryWriter(),
	): BinaryWriter {
		if (message.workerSpec !== undefined) {
			WorkerSpec.encode(message.workerSpec, writer.uint32(10).fork()).join();
		}
		if (message.rpcMessage !== undefined) {
			writer.uint32(18).bytes(message.rpcMessage);
		}
		return writer;
	},

	decode(input: BinaryReader | Uint8Array, length?: number): CommandPayload {
		const reader =
			input instanceof BinaryReader ? input : new BinaryReader(input);
		const end = length === undefined ? reader.len : reader.pos + length;
		const message = createBaseCommandPayload();
		while (reader.pos < end) {
			const tag = reader.uint32();
			switch (tag >>> 3) {
				case 1: {
					if (tag !== 10) {
						break;
					}

					message.workerSpec = WorkerSpec.decode(reader, reader.uint32());
					continue;
				}
				case 2: {
					if (tag !== 18) {
						break;
					}

					message.rpcMessage = reader.bytes();
					continue;
				}
			}
			if ((tag & 7) === 4 || tag === 0) {
				break;
			}
			reader.skip(tag & 7);
		}
		return message;
	},

	fromJSON(object: any): CommandPayload {
		return {
			workerSpec: isSet(object.workerSpec)
				? WorkerSpec.fromJSON(object.workerSpec)
				: isSet(object.worker_spec)
					? WorkerSpec.fromJSON(object.worker_spec)
					: undefined,
			rpcMessage: isSet(object.rpcMessage)
				? bytesFromBase64(object.rpcMessage)
				: isSet(object.rpc_message)
					? bytesFromBase64(object.rpc_message)
					: undefined,
		};
	},

	toJSON(message: CommandPayload): unknown {
		const obj: any = {};
		if (message.workerSpec !== undefined) {
			obj.workerSpec = WorkerSpec.toJSON(message.workerSpec);
		}
		if (message.rpcMessage !== undefined) {
			obj.rpcMessage = base64FromBytes(message.rpcMessage);
		}
		return obj;
	},

	create(base?: DeepPartial<CommandPayload>): CommandPayload {
		return CommandPayload.fromPartial(base ?? {});
	},
	fromPartial(object: DeepPartial<CommandPayload>): CommandPayload {
		const message = createBaseCommandPayload();
		message.workerSpec =
			object.workerSpec !== undefined && object.workerSpec !== null
				? WorkerSpec.fromPartial(object.workerSpec)
				: undefined;
		message.rpcMessage = object.rpcMessage ?? undefined;
		return message;
	},
};

function createBaseCommandRequest(): CommandRequest {
	return { rpcMessage: new Uint8Array(0) };
}

export const CommandRequest: MessageFns<CommandRequest> = {
	encode(
		message: CommandRequest,
		writer: BinaryWriter = new BinaryWriter(),
	): BinaryWriter {
		if (message.rpcMessage.length !== 0) {
			writer.uint32(10).bytes(message.rpcMessage);
		}
		return writer;
	},

	decode(input: BinaryReader | Uint8Array, length?: number): CommandRequest {
		const reader =
			input instanceof BinaryReader ? input : new BinaryReader(input);
		const end = length === undefined ? reader.len : reader.pos + length;
		const message = createBaseCommandRequest();
		while (reader.pos < end) {
			const tag = reader.uint32();
			switch (tag >>> 3) {
				case 1: {
					if (tag !== 10) {
						break;
					}

					message.rpcMessage = reader.bytes();
					continue;
				}
			}
			if ((tag & 7) === 4 || tag === 0) {
				break;
			}
			reader.skip(tag & 7);
		}
		return message;
	},

	fromJSON(object: any): CommandRequest {
		return {
			rpcMessage: isSet(object.rpcMessage)
				? bytesFromBase64(object.rpcMessage)
				: isSet(object.rpc_message)
					? bytesFromBase64(object.rpc_message)
					: new Uint8Array(0),
		};
	},

	toJSON(message: CommandRequest): unknown {
		const obj: any = {};
		if (message.rpcMessage.length !== 0) {
			obj.rpcMessage = base64FromBytes(message.rpcMessage);
		}
		return obj;
	},

	create(base?: DeepPartial<CommandRequest>): CommandRequest {
		return CommandRequest.fromPartial(base ?? {});
	},
	fromPartial(object: DeepPartial<CommandRequest>): CommandRequest {
		const message = createBaseCommandRequest();
		message.rpcMessage = object.rpcMessage ?? new Uint8Array(0);
		return message;
	},
};

function createBaseMetricsRequest(): MetricsRequest {
	return {
		cpuUsagePercent: 0,
		memoryUsagePercent: 0,
		storageUsagePercent: 0,
		score: 0,
		activeLabs: 0,
		activeNodes: 0,
	};
}

export const MetricsRequest: MessageFns<MetricsRequest> = {
	encode(
		message: MetricsRequest,
		writer: BinaryWriter = new BinaryWriter(),
	): BinaryWriter {
		if (message.cpuUsagePercent !== 0) {
			writer.uint32(9).double(message.cpuUsagePercent);
		}
		if (message.memoryUsagePercent !== 0) {
			writer.uint32(17).double(message.memoryUsagePercent);
		}
		if (message.storageUsagePercent !== 0) {
			writer.uint32(25).double(message.storageUsagePercent);
		}
		if (message.score !== 0) {
			writer.uint32(33).double(message.score);
		}
		if (message.activeLabs !== 0) {
			writer.uint32(40).int32(message.activeLabs);
		}
		if (message.activeNodes !== 0) {
			writer.uint32(48).int32(message.activeNodes);
		}
		return writer;
	},

	decode(input: BinaryReader | Uint8Array, length?: number): MetricsRequest {
		const reader =
			input instanceof BinaryReader ? input : new BinaryReader(input);
		const end = length === undefined ? reader.len : reader.pos + length;
		const message = createBaseMetricsRequest();
		while (reader.pos < end) {
			const tag = reader.uint32();
			switch (tag >>> 3) {
				case 1: {
					if (tag !== 9) {
						break;
					}

					message.cpuUsagePercent = reader.double();
					continue;
				}
				case 2: {
					if (tag !== 17) {
						break;
					}

					message.memoryUsagePercent = reader.double();
					continue;
				}
				case 3: {
					if (tag !== 25) {
						break;
					}

					message.storageUsagePercent = reader.double();
					continue;
				}
				case 4: {
					if (tag !== 33) {
						break;
					}

					message.score = reader.double();
					continue;
				}
				case 5: {
					if (tag !== 40) {
						break;
					}

					message.activeLabs = reader.int32();
					continue;
				}
				case 6: {
					if (tag !== 48) {
						break;
					}

					message.activeNodes = reader.int32();
					continue;
				}
			}
			if ((tag & 7) === 4 || tag === 0) {
				break;
			}
			reader.skip(tag & 7);
		}
		return message;
	},

	fromJSON(object: any): MetricsRequest {
		return {
			cpuUsagePercent: isSet(object.cpuUsagePercent)
				? globalThis.Number(object.cpuUsagePercent)
				: isSet(object.cpu_usage_percent)
					? globalThis.Number(object.cpu_usage_percent)
					: 0,
			memoryUsagePercent: isSet(object.memoryUsagePercent)
				? globalThis.Number(object.memoryUsagePercent)
				: isSet(object.memory_usage_percent)
					? globalThis.Number(object.memory_usage_percent)
					: 0,
			storageUsagePercent: isSet(object.storageUsagePercent)
				? globalThis.Number(object.storageUsagePercent)
				: isSet(object.storage_usage_percent)
					? globalThis.Number(object.storage_usage_percent)
					: 0,
			score: isSet(object.score) ? globalThis.Number(object.score) : 0,
			activeLabs: isSet(object.activeLabs)
				? globalThis.Number(object.activeLabs)
				: isSet(object.active_labs)
					? globalThis.Number(object.active_labs)
					: 0,
			activeNodes: isSet(object.activeNodes)
				? globalThis.Number(object.activeNodes)
				: isSet(object.active_nodes)
					? globalThis.Number(object.active_nodes)
					: 0,
		};
	},

	toJSON(message: MetricsRequest): unknown {
		const obj: any = {};
		if (message.cpuUsagePercent !== 0) {
			obj.cpuUsagePercent = message.cpuUsagePercent;
		}
		if (message.memoryUsagePercent !== 0) {
			obj.memoryUsagePercent = message.memoryUsagePercent;
		}
		if (message.storageUsagePercent !== 0) {
			obj.storageUsagePercent = message.storageUsagePercent;
		}
		if (message.score !== 0) {
			obj.score = message.score;
		}
		if (message.activeLabs !== 0) {
			obj.activeLabs = Math.round(message.activeLabs);
		}
		if (message.activeNodes !== 0) {
			obj.activeNodes = Math.round(message.activeNodes);
		}
		return obj;
	},

	create(base?: DeepPartial<MetricsRequest>): MetricsRequest {
		return MetricsRequest.fromPartial(base ?? {});
	},
	fromPartial(object: DeepPartial<MetricsRequest>): MetricsRequest {
		const message = createBaseMetricsRequest();
		message.cpuUsagePercent = object.cpuUsagePercent ?? 0;
		message.memoryUsagePercent = object.memoryUsagePercent ?? 0;
		message.storageUsagePercent = object.storageUsagePercent ?? 0;
		message.score = object.score ?? 0;
		message.activeLabs = object.activeLabs ?? 0;
		message.activeNodes = object.activeNodes ?? 0;
		return message;
	},
};

function createBaseMetricsResponse(): MetricsResponse {
	return { success: false };
}

export const MetricsResponse: MessageFns<MetricsResponse> = {
	encode(
		message: MetricsResponse,
		writer: BinaryWriter = new BinaryWriter(),
	): BinaryWriter {
		if (message.success !== false) {
			writer.uint32(8).bool(message.success);
		}
		return writer;
	},

	decode(input: BinaryReader | Uint8Array, length?: number): MetricsResponse {
		const reader =
			input instanceof BinaryReader ? input : new BinaryReader(input);
		const end = length === undefined ? reader.len : reader.pos + length;
		const message = createBaseMetricsResponse();
		while (reader.pos < end) {
			const tag = reader.uint32();
			switch (tag >>> 3) {
				case 1: {
					if (tag !== 8) {
						break;
					}

					message.success = reader.bool();
					continue;
				}
			}
			if ((tag & 7) === 4 || tag === 0) {
				break;
			}
			reader.skip(tag & 7);
		}
		return message;
	},

	fromJSON(object: any): MetricsResponse {
		return {
			success: isSet(object.success)
				? globalThis.Boolean(object.success)
				: false,
		};
	},

	toJSON(message: MetricsResponse): unknown {
		const obj: any = {};
		if (message.success !== false) {
			obj.success = message.success;
		}
		return obj;
	},

	create(base?: DeepPartial<MetricsResponse>): MetricsResponse {
		return MetricsResponse.fromPartial(base ?? {});
	},
	fromPartial(object: DeepPartial<MetricsResponse>): MetricsResponse {
		const message = createBaseMetricsResponse();
		message.success = object.success ?? false;
		return message;
	},
};

export type WorkerServiceDefinition = typeof WorkerServiceDefinition;
export const WorkerServiceDefinition = {
	name: "WorkerService",
	fullName: "vlab.worker.WorkerService",
	methods: {
		listenCommand: {
			name: "ListenCommand",
			requestType: CommandPayload as typeof CommandPayload,
			requestStream: true,
			responseType: CommandRequest as typeof CommandRequest,
			responseStream: true,
			options: {},
		},
		sendMetrics: {
			name: "SendMetrics",
			requestType: MetricsRequest as typeof MetricsRequest,
			requestStream: false,
			responseType: MetricsResponse as typeof MetricsResponse,
			responseStream: false,
			options: {},
		},
	},
} as const;

export interface WorkerServiceImplementation<CallContextExt = {}> {
	listenCommand(
		request: AsyncIterable<CommandPayload>,
		context: CallContext & CallContextExt,
	): ServerStreamingMethodResult<DeepPartial<CommandRequest>>;
	sendMetrics(
		request: MetricsRequest,
		context: CallContext & CallContextExt,
	): Promise<DeepPartial<MetricsResponse>>;
}

export interface WorkerServiceClient<CallOptionsExt = {}> {
	listenCommand(
		request: AsyncIterable<DeepPartial<CommandPayload>>,
		options?: CallOptions & CallOptionsExt,
	): AsyncIterable<CommandRequest>;
	sendMetrics(
		request: DeepPartial<MetricsRequest>,
		options?: CallOptions & CallOptionsExt,
	): Promise<MetricsResponse>;
}

function bytesFromBase64(b64: string): Uint8Array {
	if ((globalThis as any).Buffer) {
		return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
	} else {
		const bin = globalThis.atob(b64);
		const arr = new Uint8Array(bin.length);
		for (let i = 0; i < bin.length; ++i) {
			arr[i] = bin.charCodeAt(i);
		}
		return arr;
	}
}

function base64FromBytes(arr: Uint8Array): string {
	if ((globalThis as any).Buffer) {
		return (globalThis as any).Buffer.from(arr).toString("base64");
	} else {
		const bin: string[] = [];
		arr.forEach((byte) => {
			bin.push(globalThis.String.fromCharCode(byte));
		});
		return globalThis.btoa(bin.join(""));
	}
}

type Builtin =
	| Date
	| Function
	| Uint8Array
	| string
	| number
	| boolean
	| undefined;

export type DeepPartial<T> = T extends Builtin
	? T
	: T extends globalThis.Array<infer U>
		? globalThis.Array<DeepPartial<U>>
		: T extends ReadonlyArray<infer U>
			? ReadonlyArray<DeepPartial<U>>
			: T extends {}
				? { [K in keyof T]?: DeepPartial<T[K]> }
				: Partial<T>;

function isSet(value: any): boolean {
	return value !== null && value !== undefined;
}

export type ServerStreamingMethodResult<Response> = {
	[Symbol.asyncIterator](): AsyncIterator<Response, void>;
};

export interface MessageFns<T> {
	encode(message: T, writer?: BinaryWriter): BinaryWriter;
	decode(input: BinaryReader | Uint8Array, length?: number): T;
	fromJSON(object: any): T;
	toJSON(message: T): unknown;
	create(base?: DeepPartial<T>): T;
	fromPartial(object: DeepPartial<T>): T;
}
