/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardadminUserStudentIndexRouteImport } from './routes/_dashboard/(admin)/user/student/index'
import { Route as DashboardadminUserInstructorIndexRouteImport } from './routes/_dashboard/(admin)/user/instructor/index'
import { Route as DashboardadminUserAdminIndexRouteImport } from './routes/_dashboard/(admin)/user/admin/index'
import { Route as DashboardadminMasterStudyProgramIndexRouteImport } from './routes/_dashboard/(admin)/master/study-program/index'
import { Route as DashboardadminMasterDepartmentIndexRouteImport } from './routes/_dashboard/(admin)/master/department/index'
import { Route as DashboardadminLabDataDeviceTemplateIndexRouteImport } from './routes/_dashboard/(admin)/lab-data/device-template/index'
import { Route as DashboardadminLabDataDeviceCategoryIndexRouteImport } from './routes/_dashboard/(admin)/lab-data/device-category/index'
import { Route as DashboardadminLabDataDeviceTemplateCreateRouteImport } from './routes/_dashboard/(admin)/lab-data/device-template/create'
import { Route as DashboardadminLabDataDeviceTemplateIdEditRouteImport } from './routes/_dashboard/(admin)/lab-data/device-template/$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardadminUserStudentIndexRoute =
  DashboardadminUserStudentIndexRouteImport.update({
    id: '/(admin)/user/student/',
    path: '/user/student/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardadminUserInstructorIndexRoute =
  DashboardadminUserInstructorIndexRouteImport.update({
    id: '/(admin)/user/instructor/',
    path: '/user/instructor/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardadminUserAdminIndexRoute =
  DashboardadminUserAdminIndexRouteImport.update({
    id: '/(admin)/user/admin/',
    path: '/user/admin/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardadminMasterStudyProgramIndexRoute =
  DashboardadminMasterStudyProgramIndexRouteImport.update({
    id: '/(admin)/master/study-program/',
    path: '/master/study-program/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardadminMasterDepartmentIndexRoute =
  DashboardadminMasterDepartmentIndexRouteImport.update({
    id: '/(admin)/master/department/',
    path: '/master/department/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardadminLabDataDeviceTemplateIndexRoute =
  DashboardadminLabDataDeviceTemplateIndexRouteImport.update({
    id: '/(admin)/lab-data/device-template/',
    path: '/lab-data/device-template/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardadminLabDataDeviceCategoryIndexRoute =
  DashboardadminLabDataDeviceCategoryIndexRouteImport.update({
    id: '/(admin)/lab-data/device-category/',
    path: '/lab-data/device-category/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardadminLabDataDeviceTemplateCreateRoute =
  DashboardadminLabDataDeviceTemplateCreateRouteImport.update({
    id: '/(admin)/lab-data/device-template/create',
    path: '/lab-data/device-template/create',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardadminLabDataDeviceTemplateIdEditRoute =
  DashboardadminLabDataDeviceTemplateIdEditRouteImport.update({
    id: '/(admin)/lab-data/device-template/$id/edit',
    path: '/lab-data/device-template/$id/edit',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/lab-data/device-template/create': typeof DashboardadminLabDataDeviceTemplateCreateRoute
  '/lab-data/device-category/': typeof DashboardadminLabDataDeviceCategoryIndexRoute
  '/lab-data/device-template/': typeof DashboardadminLabDataDeviceTemplateIndexRoute
  '/master/department/': typeof DashboardadminMasterDepartmentIndexRoute
  '/master/study-program/': typeof DashboardadminMasterStudyProgramIndexRoute
  '/user/admin/': typeof DashboardadminUserAdminIndexRoute
  '/user/instructor/': typeof DashboardadminUserInstructorIndexRoute
  '/user/student/': typeof DashboardadminUserStudentIndexRoute
  '/lab-data/device-template/$id/edit': typeof DashboardadminLabDataDeviceTemplateIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof DashboardIndexRoute
  '/lab-data/device-template/create': typeof DashboardadminLabDataDeviceTemplateCreateRoute
  '/lab-data/device-category': typeof DashboardadminLabDataDeviceCategoryIndexRoute
  '/lab-data/device-template': typeof DashboardadminLabDataDeviceTemplateIndexRoute
  '/master/department': typeof DashboardadminMasterDepartmentIndexRoute
  '/master/study-program': typeof DashboardadminMasterStudyProgramIndexRoute
  '/user/admin': typeof DashboardadminUserAdminIndexRoute
  '/user/instructor': typeof DashboardadminUserInstructorIndexRoute
  '/user/student': typeof DashboardadminUserStudentIndexRoute
  '/lab-data/device-template/$id/edit': typeof DashboardadminLabDataDeviceTemplateIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/(admin)/lab-data/device-template/create': typeof DashboardadminLabDataDeviceTemplateCreateRoute
  '/_dashboard/(admin)/lab-data/device-category/': typeof DashboardadminLabDataDeviceCategoryIndexRoute
  '/_dashboard/(admin)/lab-data/device-template/': typeof DashboardadminLabDataDeviceTemplateIndexRoute
  '/_dashboard/(admin)/master/department/': typeof DashboardadminMasterDepartmentIndexRoute
  '/_dashboard/(admin)/master/study-program/': typeof DashboardadminMasterStudyProgramIndexRoute
  '/_dashboard/(admin)/user/admin/': typeof DashboardadminUserAdminIndexRoute
  '/_dashboard/(admin)/user/instructor/': typeof DashboardadminUserInstructorIndexRoute
  '/_dashboard/(admin)/user/student/': typeof DashboardadminUserStudentIndexRoute
  '/_dashboard/(admin)/lab-data/device-template/$id/edit': typeof DashboardadminLabDataDeviceTemplateIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/lab-data/device-template/create'
    | '/lab-data/device-category/'
    | '/lab-data/device-template/'
    | '/master/department/'
    | '/master/study-program/'
    | '/user/admin/'
    | '/user/instructor/'
    | '/user/student/'
    | '/lab-data/device-template/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/lab-data/device-template/create'
    | '/lab-data/device-category'
    | '/lab-data/device-template'
    | '/master/department'
    | '/master/study-program'
    | '/user/admin'
    | '/user/instructor'
    | '/user/student'
    | '/lab-data/device-template/$id/edit'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/'
    | '/_dashboard/(admin)/lab-data/device-template/create'
    | '/_dashboard/(admin)/lab-data/device-category/'
    | '/_dashboard/(admin)/lab-data/device-template/'
    | '/_dashboard/(admin)/master/department/'
    | '/_dashboard/(admin)/master/study-program/'
    | '/_dashboard/(admin)/user/admin/'
    | '/_dashboard/(admin)/user/instructor/'
    | '/_dashboard/(admin)/user/student/'
    | '/_dashboard/(admin)/lab-data/device-template/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/(admin)/user/student/': {
      id: '/_dashboard/(admin)/user/student/'
      path: '/user/student'
      fullPath: '/user/student/'
      preLoaderRoute: typeof DashboardadminUserStudentIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/(admin)/user/instructor/': {
      id: '/_dashboard/(admin)/user/instructor/'
      path: '/user/instructor'
      fullPath: '/user/instructor/'
      preLoaderRoute: typeof DashboardadminUserInstructorIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/(admin)/user/admin/': {
      id: '/_dashboard/(admin)/user/admin/'
      path: '/user/admin'
      fullPath: '/user/admin/'
      preLoaderRoute: typeof DashboardadminUserAdminIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/(admin)/master/study-program/': {
      id: '/_dashboard/(admin)/master/study-program/'
      path: '/master/study-program'
      fullPath: '/master/study-program/'
      preLoaderRoute: typeof DashboardadminMasterStudyProgramIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/(admin)/master/department/': {
      id: '/_dashboard/(admin)/master/department/'
      path: '/master/department'
      fullPath: '/master/department/'
      preLoaderRoute: typeof DashboardadminMasterDepartmentIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/(admin)/lab-data/device-template/': {
      id: '/_dashboard/(admin)/lab-data/device-template/'
      path: '/lab-data/device-template'
      fullPath: '/lab-data/device-template/'
      preLoaderRoute: typeof DashboardadminLabDataDeviceTemplateIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/(admin)/lab-data/device-category/': {
      id: '/_dashboard/(admin)/lab-data/device-category/'
      path: '/lab-data/device-category'
      fullPath: '/lab-data/device-category/'
      preLoaderRoute: typeof DashboardadminLabDataDeviceCategoryIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/(admin)/lab-data/device-template/create': {
      id: '/_dashboard/(admin)/lab-data/device-template/create'
      path: '/lab-data/device-template/create'
      fullPath: '/lab-data/device-template/create'
      preLoaderRoute: typeof DashboardadminLabDataDeviceTemplateCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/(admin)/lab-data/device-template/$id/edit': {
      id: '/_dashboard/(admin)/lab-data/device-template/$id/edit'
      path: '/lab-data/device-template/$id/edit'
      fullPath: '/lab-data/device-template/$id/edit'
      preLoaderRoute: typeof DashboardadminLabDataDeviceTemplateIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardadminLabDataDeviceTemplateCreateRoute: typeof DashboardadminLabDataDeviceTemplateCreateRoute
  DashboardadminLabDataDeviceCategoryIndexRoute: typeof DashboardadminLabDataDeviceCategoryIndexRoute
  DashboardadminLabDataDeviceTemplateIndexRoute: typeof DashboardadminLabDataDeviceTemplateIndexRoute
  DashboardadminMasterDepartmentIndexRoute: typeof DashboardadminMasterDepartmentIndexRoute
  DashboardadminMasterStudyProgramIndexRoute: typeof DashboardadminMasterStudyProgramIndexRoute
  DashboardadminUserAdminIndexRoute: typeof DashboardadminUserAdminIndexRoute
  DashboardadminUserInstructorIndexRoute: typeof DashboardadminUserInstructorIndexRoute
  DashboardadminUserStudentIndexRoute: typeof DashboardadminUserStudentIndexRoute
  DashboardadminLabDataDeviceTemplateIdEditRoute: typeof DashboardadminLabDataDeviceTemplateIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardadminLabDataDeviceTemplateCreateRoute:
    DashboardadminLabDataDeviceTemplateCreateRoute,
  DashboardadminLabDataDeviceCategoryIndexRoute:
    DashboardadminLabDataDeviceCategoryIndexRoute,
  DashboardadminLabDataDeviceTemplateIndexRoute:
    DashboardadminLabDataDeviceTemplateIndexRoute,
  DashboardadminMasterDepartmentIndexRoute:
    DashboardadminMasterDepartmentIndexRoute,
  DashboardadminMasterStudyProgramIndexRoute:
    DashboardadminMasterStudyProgramIndexRoute,
  DashboardadminUserAdminIndexRoute: DashboardadminUserAdminIndexRoute,
  DashboardadminUserInstructorIndexRoute:
    DashboardadminUserInstructorIndexRoute,
  DashboardadminUserStudentIndexRoute: DashboardadminUserStudentIndexRoute,
  DashboardadminLabDataDeviceTemplateIdEditRoute:
    DashboardadminLabDataDeviceTemplateIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
