/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

import type { ContainerlabTopology } from "./types";

export interface paths {
	"/api/v1/events": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Stream containerlab events
		 * @description Streams containerlab events in real time as NDJSON (one JSON object per line).
		 *
		 *     **Notes**
		 *     - The response stays open until the client disconnects.
		 *
		 *     **Examples**
		 *     NDJSON (one JSON object per line):
		 *     ```json
		 *     {"time":1706918400,"type":"container","action":"start","attributes":{"name":"clab-mylab-srl1","lab":"mylab","clab-node-name":"srl1","clab-node-kind":"nokia_srlinux"}}
		 *     {"time":1706918405,"type":"container","action":"start","attributes":{"name":"clab-mylab-srl2","lab":"mylab","clab-node-name":"srl2","clab-node-kind":"nokia_srlinux"}}
		 *     ```
		 *
		 *
		 *     Interface stats (interfaceStats=true):
		 *     ```json
		 *     {"time":1706918410,"type":"interface-stats","action":"stats","attributes":{"name":"clab-mylab-srl1","lab":"mylab","interface":"e1-1","rx_bytes":123456,"tx_bytes":654321}}
		 *     ```
		 */
		get: {
			parameters: {
				query?: {
					/** @description Include initial snapshot events when the stream starts. */
					initialState?: boolean;
					/** @description Include interface stats events. */
					interfaceStats?: boolean;
					/** @description Interval for interface stats collection (e.g., 10s). Requires interfaceStats=true. */
					interfaceStatsInterval?: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Event stream - NDJSON (one JSON object per line) */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/x-ndjson": components["schemas"]["models.EventResponse"];
					};
				};
				/** @description Invalid input */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/x-ndjson": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/x-ndjson": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/x-ndjson": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/generate": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Generate containerlab topology
		 * @description Generates a containerlab topology from CLOS definitions and can optionally deploy it for the authenticated user.
		 *
		 *     **Notes**
		 *     - Deployment is denied if a lab with the target name already exists.
		 *     - The `images` and `licenses` fields map node kind to image or license path (e.g., {"nokia_srlinux":"ghcr.io/..."}).
		 *     - When `deploy=true`, the topology is saved to the user's `~/.clab/<labName>/` directory and `outputFile` is ignored.
		 *     - When `deploy=false` and `outputFile` is empty, YAML is returned in the response.
		 *     - When `deploy=false` and `outputFile` is set, the file is saved to that path on the server (requires API server write permissions).
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Topology generation parameters. The 'images' field maps kind to image path. */
			requestBody: {
				content: {
					"application/json": components["schemas"]["models.GenerateRequest"];
				};
			};
			responses: {
				/** @description Generation successful (YAML or deploy output) */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.GenerateResponse"];
					};
				};
				/** @description Invalid input parameters */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Conflict (Lab already exists and Deploy=true) */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error or clab execution failed */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/health/metrics": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get system metrics
		 * @description Returns detailed CPU, memory, and disk metrics for the API server. Requires superuser privileges.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description System metrics */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.MetricsResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (User is not a superuser) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error gathering metrics */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/labs": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List labs
		 * @description Returns details for all running labs.
		 *
		 *     **Notes**
		 *     - Results are filtered by owner unless the caller is a superuser.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description All labs */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ClabInspectOutput"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		/**
		 * Deploy lab
		 * @description Deploys a containerlab topology.
		 *
		 *     **Notes**
		 *     - The request body must include either `topologyContent` or `topologySourceUrl` (not both).
		 */
		post: {
			parameters: {
				query?: {
					/** @description Override lab name when deploying from a URL (optional) */
					labNameOverride?: string;
					/** @description Allow overwriting an existing lab IF owned by the user */
					reconfigure?: boolean;
					/** @description Limit concurrent workers */
					maxWorkers?: number;
					/** @description Custom Go template file for topology data export */
					exportTemplate?: string;
					/** @description Comma-separated list of node names to deploy */
					nodeFilter?: string;
					/** @description Skip post-deploy actions */
					skipPostDeploy?: boolean;
					/** @description Skip setting extended ACLs on lab directory */
					skipLabdirAcl?: boolean;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Deployment Source */
			requestBody: {
				content: {
					"application/json": components["schemas"]["models.DeployRequest"];
				};
			};
			responses: {
				/** @description Deployed lab details */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ClabInspectOutput"];
					};
				};
				/** @description Invalid input */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Conflict */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/labs/archive": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Deploy lab from archive
		 * @description Deploys a containerlab topology provided as a .zip or .tar.gz archive.
		 */
		post: {
			parameters: {
				query: {
					/** @description Name for the lab */
					labName: string;
					/** @description Allow overwriting an existing lab */
					reconfigure?: boolean;
					/** @description Limit concurrent workers */
					maxWorkers?: number;
					/** @description Custom Go template file for topology data export */
					exportTemplate?: string;
					/** @description Comma-separated list of node names to deploy */
					nodeFilter?: string;
					/** @description Skip post-deploy actions */
					skipPostDeploy?: boolean;
					/** @description Skip setting extended ACLs on lab directory */
					skipLabdirAcl?: boolean;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"multipart/form-data": {
						/**
						 * Format: binary
						 * @description Lab archive (.zip or .tar.gz)
						 */
						labArchive: string;
					};
				};
			};
			responses: {
				/** @description Deployed lab details */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ClabInspectOutput"];
					};
				};
				/** @description Invalid input */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Conflict */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/labs/{labName}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Inspect lab
		 * @description Returns details for a specific running lab.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Name of the lab to inspect */
					labName: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Lab containers */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ClabContainerInfo"][];
					};
				};
				/** @description Invalid lab name */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Lab not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		/**
		 * Redeploy lab
		 * @description Redeploys a lab by name.
		 *
		 *     **Notes**
		 *     - This operation destroys the lab and then deploys it again.
		 */
		put: {
			parameters: {
				query?: {
					/** @description Remove containerlab lab artifacts during destroy phase */
					cleanup?: boolean;
					/** @description Attempt graceful shutdown */
					graceful?: boolean;
					/** @description Keep the management network */
					keepMgmtNet?: boolean;
					/** @description Limit concurrent workers */
					maxWorkers?: number;
					/** @description Custom Go template file for topology data export */
					exportTemplate?: string;
					/** @description Skip post-deploy actions */
					skipPostDeploy?: boolean;
					/** @description Skip setting extended ACLs on lab directory */
					skipLabdirAcl?: boolean;
				};
				header?: never;
				path: {
					/** @description Name of the lab to redeploy */
					labName: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Redeployed lab details */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ClabInspectOutput"];
					};
				};
				/** @description Invalid lab name */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Lab not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		post?: never;
		/**
		 * Destroy lab
		 * @description Destroys a lab by name after verifying ownership.
		 */
		delete: {
			parameters: {
				query?: {
					/** @description Remove containerlab lab artifacts after destroy */
					cleanup?: boolean;
					/** @description Purge topology parent directory for managed lab paths (~/.clab or shared labs dir) */
					purgeLabDir?: boolean;
					/** @description Attempt graceful shutdown */
					graceful?: boolean;
					/** @description Keep the management network */
					keepMgmtNet?: boolean;
					/** @description Destroy only specific nodes */
					nodeFilter?: string;
				};
				header?: never;
				path: {
					/** @description Name of the lab to destroy */
					labName: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Lab destroyed successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.GenericSuccessResponse"];
					};
				};
				/** @description Invalid lab name */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Lab not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/labs/{labName}/exec": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Execute command in lab
		 * @description Executes a command on nodes within a lab.
		 */
		post: {
			parameters: {
				query?: {
					/** @description Execute only on this specific node */
					nodeFilter?: string;
				};
				header?: never;
				path: {
					/** @description Name of the lab */
					labName: string;
				};
				cookie?: never;
			};
			/** @description Command to execute */
			requestBody: {
				content: {
					"application/json": components["schemas"]["models.ExecRequest"];
				};
			};
			responses: {
				/** @description Execution result */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ExecResponse"];
					};
				};
				/** @description Invalid input */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Lab not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/labs/{labName}/interfaces": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List lab interfaces
		 * @description Returns interface details for nodes in a lab.
		 */
		get: {
			parameters: {
				query?: {
					/** @description Filter interfaces for a specific node */
					node?: string;
				};
				header?: never;
				path: {
					/** @description Name of the lab */
					labName: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Interface details */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.NodeInterfaceInfo"][];
					};
				};
				/** @description Invalid lab name */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Lab not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/labs/{labName}/nodes/{nodeName}/logs": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get node logs
		 * @description Returns logs for a lab node.
		 *
		 *     **Notes**
		 *     - When `follow=true`, the response streams as NDJSON (one JSON object per line) until the client disconnects or the 30-minute timeout.
		 */
		get: {
			parameters: {
				query?: {
					/** @description Number of lines to show from the end of logs (default all). Use an integer or 'all'. */
					tail?: string;
					/** @description Follow log output (stream logs as NDJSON). Note: In Swagger UI, streaming may not display correctly. */
					follow?: boolean;
				};
				header?: never;
				path: {
					/** @description Name of the lab */
					labName: string;
					/** @description Full name of the container (node) */
					nodeName: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Container logs (follow=false). When follow=true, response is NDJSON stream of LogLine objects. */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.LogsResponse"];
						"application/x-ndjson": components["schemas"]["models.LogsResponse"];
					};
				};
				/** @description Invalid input (lab name, node filter, etc.) */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
						"application/x-ndjson": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
						"application/x-ndjson": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (not owner of the lab) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
						"application/x-ndjson": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Lab or node not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
						"application/x-ndjson": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
						"application/x-ndjson": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/labs/{labName}/nodes/{nodeName}/ssh": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Request SSH access to lab node
		 * @description Creates temporary SSH access to a lab node and returns connection details.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Lab name */
					labName: string;
					/** @description Full container name of the node (e.g., clab-my-lab-srl1) */
					nodeName: string;
				};
				cookie?: never;
			};
			/** @description SSH access parameters */
			requestBody?: {
				content: {
					"application/json": components["schemas"]["models.SSHAccessRequest"];
				};
			};
			responses: {
				/** @description SSH connection details */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.SSHAccessResponse"];
					};
				};
				/** @description Invalid request parameters */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (not owner of the lab) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Lab or node not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/labs/{labName}/save": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Save lab configuration
		 * @description Saves the running configuration for nodes in a lab.
		 */
		post: {
			parameters: {
				query?: {
					/** @description Save config only for specific nodes */
					nodeFilter?: string;
				};
				header?: never;
				path: {
					/** @description Name of the lab */
					labName: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Configuration saved */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.SaveConfigResponse"];
					};
				};
				/** @description Invalid input */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Lab not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/ssh/sessions": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List SSH sessions
		 * @description Returns active SSH sessions.
		 *
		 *     **Notes**
		 *     - Regular users see only their sessions.
		 *     - Superusers can include all sessions via the `all` query parameter.
		 */
		get: {
			parameters: {
				query?: {
					/** @description If true and user is superuser, shows sessions for all users (default: false) */
					all?: boolean;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of active SSH sessions */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.SSHSessionInfo"][];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (non-superuser attempting to list all sessions) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/ssh/sessions/{port}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Terminate SSH session
		 * @description Terminates a specific SSH session by port.
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description SSH session port to terminate */
					port: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Session terminated successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.GenericSuccessResponse"];
					};
				};
				/** @description Invalid port parameter */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (not owner of the session) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Session not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tools/certs/ca": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create certificate authority (CA)
		 * @description Creates a CA certificate and private key. Requires superuser privileges.
		 *
		 *     **Notes**
		 *     - Files are stored in the user's `~/.clab/certs/<ca_name>/` directory on the server.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description CA Generation Parameters */
			requestBody: {
				content: {
					"application/json": components["schemas"]["models.CACreateRequest"];
				};
			};
			responses: {
				/** @description CA created successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.CertResponse"];
					};
				};
				/** @description Invalid input parameters */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized (JWT) */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (User is not a superuser) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error (filesystem, clab execution) */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tools/certs/sign": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Sign certificate
		 * @description Creates a certificate/key and signs it with a previously generated CA. Requires superuser privileges.
		 *
		 *     **Notes**
		 *     - Files are stored in the user's `~/.clab/certs/<ca_name>/` directory.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Certificate Signing Parameters */
			requestBody: {
				content: {
					"application/json": components["schemas"]["models.CertSignRequest"];
				};
			};
			responses: {
				/** @description Certificate signed successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.CertResponse"];
					};
				};
				/** @description Invalid input parameters (name, hosts, CA name, etc.) */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized (JWT) */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (User is not a superuser) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Specified CA not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error (filesystem, clab execution) */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tools/disable-tx-offload": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Disable TX checksum offload
		 * @description Disables TX checksum offload on the eth0 interface of a container. Requires superuser privileges.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Container Name */
			requestBody: {
				content: {
					"application/json": components["schemas"]["models.DisableTxOffloadRequest"];
				};
			};
			responses: {
				/** @description Offload disabled successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.GenericSuccessResponse"];
					};
				};
				/** @description Invalid input */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized (JWT) */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (User is not a superuser) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Container not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error or clab execution failed */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tools/netem/reset": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Reset link impairments (netem)
		 * @description Resets (removes) netem impairments from a specific interface of a containerlab node. Requires superuser privileges.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Netem Reset Parameters */
			requestBody: {
				content: {
					"application/json": components["schemas"]["models.NetemResetRequest"];
				};
			};
			responses: {
				/** @description Impairments reset successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.GenericSuccessResponse"];
					};
				};
				/** @description Invalid input parameters */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized (JWT) */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (User is not a superuser) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Container or interface not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tools/netem/set": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Set link impairments (netem)
		 * @description Sets netem impairments (delay, jitter, loss, rate limiting, corruption) on a specific interface of a containerlab node. Requires superuser privileges.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Netem Set Parameters */
			requestBody: {
				content: {
					"application/json": components["schemas"]["models.NetemSetRequest"];
				};
			};
			responses: {
				/** @description Impairments set successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.GenericSuccessResponse"];
					};
				};
				/** @description Invalid input parameters */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized (JWT) */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (User is not a superuser) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Container or interface not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tools/netem/show": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Show link impairments (netem)
		 * @description Lists netem impairments for a given containerlab node. Requires superuser privileges.
		 */
		get: {
			parameters: {
				query: {
					/** @description Container/node name */
					containerName: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Netem impairments */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.NetemShowResponse"];
					};
				};
				/** @description Invalid input parameters */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized (JWT) */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (User is not a superuser) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Container not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tools/veth": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create vEth pair
		 * @description Creates a virtual Ethernet (vEth) pair between two endpoints (container, host, bridge, or ovs-bridge). Requires superuser privileges.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description vEth Creation Parameters */
			requestBody: {
				content: {
					"application/json": components["schemas"]["models.VethCreateRequest"];
				};
			};
			responses: {
				/** @description vEth pair created successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.GenericSuccessResponse"];
					};
				};
				/** @description Invalid input parameters (endpoints, MTU) */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized (JWT) */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (User is not a superuser) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error (clab execution failed) */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/tools/vxlan": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create VxLAN tunnel
		 * @description Creates a VxLAN tunnel interface and sets up tc rules for traffic redirection. Requires superuser privileges.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description VxLAN Creation Parameters */
			requestBody: {
				content: {
					"application/json": components["schemas"]["models.VxlanCreateRequest"];
				};
			};
			responses: {
				/** @description VxLAN tunnel created successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.GenericSuccessResponse"];
					};
				};
				/** @description Invalid input parameters (remote, link, id, port, etc.) */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized (JWT) */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (User is not a superuser) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error (clab execution failed) */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		/**
		 * Delete VxLAN tunnels by prefix
		 * @description Deletes VxLAN tunnel interfaces that match the provided prefix (default: `vx-`). Requires superuser privileges.
		 */
		delete: {
			parameters: {
				query?: {
					/** @description Prefix of VxLAN interfaces to delete */
					prefix?: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description VxLAN tunnels deleted successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.GenericSuccessResponse"];
					};
				};
				/** @description Invalid prefix format */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized (JWT) */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (User is not a superuser) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error (clab execution failed) */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List users
		 * @description Returns a list of system users. Requires superuser privileges.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of user details */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.UserDetails"][];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (User is not a superuser) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		/**
		 * Create user
		 * @description Creates a new system user. Requires superuser privileges.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description User creation details */
			requestBody: {
				content: {
					"application/json": components["schemas"]["models.UserCreateRequest"];
				};
			};
			responses: {
				/** @description User created successfully */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.GenericSuccessResponse"];
					};
				};
				/** @description Invalid request body */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (User is not a superuser) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description User already exists */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/{username}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get user details
		 * @description Returns details for a specific user. Requires superuser privileges or the user's own account.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Username to get details for */
					username: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description User details */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.UserDetails"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (Not superuser or not the user's own account) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description User not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		/**
		 * Update user
		 * @description Updates an existing user. Requires superuser privileges or the user's own account.
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Username to update */
					username: string;
				};
				cookie?: never;
			};
			/** @description User details to update */
			requestBody: {
				content: {
					"application/json": components["schemas"]["models.UserUpdateRequest"];
				};
			};
			responses: {
				/** @description User updated successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.GenericSuccessResponse"];
					};
				};
				/** @description Invalid request body */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (Not superuser or not the user's own account) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description User not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		post?: never;
		/**
		 * Delete user
		 * @description Deletes a user from the system. Requires superuser privileges.
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Username to delete */
					username: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description User deleted successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.GenericSuccessResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (User is not a superuser) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description User not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/{username}/password": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/**
		 * Change user password
		 * @description Changes a user's password. Requires superuser privileges or the user's own account.
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Username to change password for */
					username: string;
				};
				cookie?: never;
			};
			/** @description Password change details */
			requestBody: {
				content: {
					"application/json": components["schemas"]["models.PasswordChangeRequest"];
				};
			};
			responses: {
				/** @description Password changed successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.GenericSuccessResponse"];
					};
				};
				/** @description Invalid request body */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Unauthorized or incorrect current password */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Forbidden (Not superuser or not the user's own account) */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description User not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/version": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get containerlab version
		 * @description Returns version information for the containerlab library in use.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Containerlab version details */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.VersionResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/version/check": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Check containerlab updates
		 * @description Checks whether a newer containerlab release is available.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Result of the version check */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.VersionCheckResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/health": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get API server health
		 * @description Returns basic health status for the API server.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Basic health information */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.HealthResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Log in
		 * @description Authenticates a user and returns a JWT token.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description User Credentials */
			requestBody: {
				content: {
					"application/json": components["schemas"]["models.LoginRequest"];
				};
			};
			responses: {
				/** @description JWT token */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.LoginResponse"];
					};
				};
				/** @description Invalid input */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Invalid credentials */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
				/** @description Internal server error (PAM config?) */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["models.ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		"models.CACreateRequest": {
			/**
			 * @description Defaults to "containerlab.dev"
			 * @example ca.example.com
			 */
			commonName?: string;
			/**
			 * @description Defaults to "Internet"
			 * @example US
			 */
			country?: string;
			/**
			 * @description Duration string, defaults to "87600h" (10 years)
			 * @example 8760h
			 */
			expiry?: string;
			/**
			 * @description Defaults to "Server"
			 * @example City
			 */
			locality?: string;
			/**
			 * @description Defaults to "ca" if empty
			 * @example my-root-ca
			 */
			name?: string;
			/**
			 * @description Defaults to "Containerlab Tools"
			 * @example IT
			 */
			orgUnit?: string;
			/**
			 * @description Defaults to "Containerlab"
			 * @example MyOrg
			 */
			organization?: string;
		};
		"models.CPUMetrics": {
			/** @description 1-minute load average */
			loadAvg1?: number;
			/** @description 15-minute load average */
			loadAvg15?: number;
			/** @description 5-minute load average */
			loadAvg5?: number;
			/** @description Number of CPUs/cores */
			numCPU?: number;
			/** @description This process's CPU usage */
			processPercent?: number;
			/** @description Overall CPU usage percentage */
			usagePercent?: number;
		};
		"models.CertResponse": {
			/** @description e.g., "my-root-ca/my-root-ca.pem" or "my-root-ca/node1.example.com.pem" */
			certPath?: string;
			/** @description e.g., "my-root-ca/my-root-ca.csr" or "my-root-ca/node1.example.com.csr" */
			csrPath?: string;
			/** @description e.g., "my-root-ca/my-root-ca.key" or "my-root-ca/node1.example.com.key" */
			keyPath?: string;
			message?: string;
		};
		"models.CertSignRequest": {
			/**
			 * @description Name of the CA cert/key files (without .pem/.key) previously generated
			 * @example my-root-ca
			 */
			caName: string;
			/**
			 * @description Defaults to Name if empty
			 * @example node1.example.com
			 */
			commonName?: string;
			/**
			 * @description Defaults to "Internet"
			 * @example US
			 */
			country?: string;
			/** @description SANs (DNS names or IPs), comma-separated in clab, array here */
			hosts: string[];
			/**
			 * @description Defaults to 2048
			 * @example 4096
			 */
			keySize?: number;
			/**
			 * @description Defaults to "Server"
			 * @example City
			 */
			locality?: string;
			/**
			 * @description Required
			 * @example node1.example.com
			 */
			name: string;
			/**
			 * @description Defaults to "Containerlab Tools"
			 * @example Nodes
			 */
			orgUnit?: string;
			/**
			 * @description Defaults to "Containerlab"
			 * @example MyOrg
			 */
			organization?: string;
		};
		"models.ClabContainerInfo": {
			/** @description Absolute path to topology file */
			absLabPath?: string;
			/** @description Docker container ID (short) */
			container_id?: string;
			/** @description Group assigned in topology (Might not always be present) */
			group?: string;
			/** @description Container image used */
			image?: string;
			/** @description Management IPv4 Address/Mask */
			ipv4_address?: string;
			/** @description Management IPv6 Address/Mask */
			ipv6_address?: string;
			/** @description e.g., "linux", "nokia_srlinux" */
			kind?: string;
			/** @description Path to the topology file used (relative) */
			labPath?: string;
			/** @description Name of the lab this node belongs to (redundant with map key but present) */
			lab_name?: string;
			/** @description Name of the container node (e.g., "lab01-client1") */
			name?: string;
			/** @description OS user from clab inspect output (Used for authorization) */
			owner?: string;
			/** @description e.g., "running" */
			state?: string;
			/** @description e.g., "Up 18 hours" */
			status?: string;
		};
		"models.ClabExecInternalResult": {
			/** @description The command and its arguments as executed */
			cmd?: string[];
			/** @description Exit code of the command inside the container */
			"return-code"?: number;
			/** @description Standard error of the command */
			stderr?: string;
			/** @description Standard output of the command */
			stdout?: string;
		};
		"models.ClabInspectOutput": {
			[key: string]: components["schemas"]["models.ClabContainerInfo"][];
		};
		"models.DeployRequest": {
			/**
			 * @description Option 1: Direct Topology Content.
			 *     Provide the full containerlab topology YAML as a json string.
			 *     If this is provided, 'topologySourceUrl' MUST be empty.
			 *     {
			 *     	"topologyContent": {
			 *     	  "name": "your-lab-name",
			 *     	  "topology": {
			 *     		"kinds": {
			 *     		  "nokia_srlinux": {
			 *     			"type": "ixrd3",
			 *     			"image": "ghcr.io/nokia/srlinux"
			 *     		  }
			 *     		},
			 *     		"nodes": {
			 *     		  "srl1": {
			 *     			"kind": "nokia_srlinux"
			 *     		  },
			 *     		  "srl2": {
			 *     			"kind": "nokia_srlinux"
			 *     		  }
			 *     		},
			 *     		"links": [
			 *     		  {
			 *     			"endpoints": [
			 *     			  "srl1:e1-1",
			 *     			  "srl2:e1-1"
			 *     			]
			 *     		  }
			 *     		]
			 *     	  }
			 *     	}
			 *       }
			 */
			topologyContent?: ContainerlabTopology;
			/**
			 * @description Option 2: Remote Topology Source URL.
			 *     Provide a URL to a Git repository, a specific .clab.yml file in Git (github/gitlab), or a raw HTTP(S) URL.
			 *     If this is provided, 'topologyContent' MUST be empty.
			 */
			topologySourceUrl?: string;
		};
		"models.DisableTxOffloadRequest": {
			/** @example clab-my-lab-srl1 */
			containerName: string;
		};
		"models.DiskMetrics": {
			/** @description Free disk space in bytes */
			freeDisk?: number;
			/** @description Mount path (usually "/") */
			path?: string;
			/** @description Total disk space in bytes */
			totalDisk?: number;
			/** @description Disk usage percentage */
			usagePercent?: number;
			/** @description Used disk space in bytes */
			usedDisk?: number;
		};
		"models.ErrorResponse": {
			/** @example Invalid credentials or user not in allowed group */
			error?: string;
		};
		"models.EventAttributes": {
			/**
			 * @description Node kind (e.g., nokia_srlinux, linux)
			 * @example nokia_srlinux
			 */
			"clab-node-kind"?: string;
			/**
			 * @description Node name within the lab
			 * @example srl1
			 */
			"clab-node-name"?: string;
			/**
			 * @description Node type
			 * @example ixrd3
			 */
			"clab-node-type"?: string;
			/**
			 * @description Alternative lab name field (containerlab label)
			 * @example mylab
			 */
			containerlab?: string;
			/**
			 * @description Exit code (for stop/die events)
			 * @example 0
			 */
			exitCode?: string;
			/**
			 * @description Container image
			 * @example ghcr.io/nokia/srlinux:latest
			 */
			image?: string;
			/**
			 * @description Lab name this event belongs to
			 * @example mylab
			 */
			lab?: string;
			/**
			 * @description Container name
			 * @example clab-mylab-srl1
			 */
			name?: string;
		};
		"models.EventResponse": {
			/**
			 * @description Event action (e.g., "start", "stop", "die", "stats")
			 * @example start
			 */
			action?: string;
			/** @description Event attributes containing details about the event */
			attributes?: components["schemas"]["models.EventAttributes"];
			/**
			 * @description Unix timestamp when the event occurred
			 * @example 1706918400
			 */
			time?: number;
			/**
			 * @description Type of event (e.g., "container", "interface-stats")
			 * @example container
			 */
			type?: string;
		};
		"models.ExecRequest": {
			/** @example ip addr show eth1 */
			command: string;
		};
		"models.ExecResponse": {
			[key: string]: components["schemas"]["models.ClabExecInternalResult"][];
		};
		"models.GenerateNodeTier": {
			/**
			 * @description Number of nodes in this tier
			 * @example 4
			 */
			count: number;
			/**
			 * @description Node kind (defaults to 'srl'/'nokia_srlinux' if omitted)
			 * @example nokia_srlinux
			 */
			kind?: string;
			/**
			 * @description Node type within the kind
			 * @example ixrd3
			 */
			type?: string;
		};
		"models.GenerateRequest": {
			/** @example nokia_srlinux */
			defaultKind?: string;
			/** @example true */
			deploy?: boolean;
			/** @example clos-tier */
			groupPrefix?: string;
			/**
			 * @example {
			 *       "nokia_srlinux": "ghcr.io/nokia/srlinux:latest"
			 *     }
			 */
			images?: {
				[key: string]: string;
			};
			/** @example 172.20.20.0/24 */
			ipv4Subnet?: string;
			/** @example 2001:172:20:20::/64 */
			ipv6Subnet?: string;
			/**
			 * @example {
			 *       "nokia_srlinux": "/opt/licenses/srl.lic"
			 *     }
			 */
			licenses?: {
				[key: string]: string;
			};
			/** @example clos-mgmt */
			managementNetwork?: string;
			/** @example 4 */
			maxWorkers?: number;
			/** @example 3-tier-clos */
			name: string;
			/** @example clos-node */
			nodePrefix?: string;
			/** @example clos.yml */
			outputFile?: string;
			tiers: components["schemas"]["models.GenerateNodeTier"][];
		};
		"models.GenerateResponse": {
			/**
			 * @description The output from the deploy command (only if Deploy=true). JSON object keyed by lab name.
			 *     Use swaggertype:"object" to represent json.RawMessage in Swagger.
			 */
			deployOutput?: Record<string, never>;
			/** @description Message indicating success or failure. */
			message?: string;
			/** @description Path where the file was saved (if Deploy=true, it's the path in the user's ~/.clab dir; if Deploy=false, it's the OutputFile path if provided). */
			savedFilePath?: string;
			/** @description The generated topology YAML (only if Deploy=false and OutputFile is empty). */
			topologyYaml?: string;
		};
		"models.GenericSuccessResponse": {
			message?: string;
		};
		"models.HealthResponse": {
			/** @description When the server started */
			startTime?: string;
			/** @description "healthy" or other status indicators */
			status?: string;
			/** @description Human-readable uptime */
			uptime?: string;
			/** @description API server version */
			version?: string;
		};
		"models.InterfaceInfo": {
			/** @description Interface alias (e.g., "ethernet-1/1", "" if none) */
			alias?: string;
			/** @description Interface index */
			ifindex?: number;
			/** @description MAC Address */
			mac?: string;
			/** @description MTU size */
			mtu?: number;
			/** @description Interface name (e.g., "eth0", "e1-1") */
			name?: string;
			/** @description Interface state (e.g., "up", "down", "unknown") */
			state?: string;
			/** @description Interface type (e.g., "veth", "device", "dummy") */
			type?: string;
		};
		"models.LoginRequest": {
			password: string;
			username: string;
		};
		"models.LoginResponse": {
			/** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNzA2OTIyMDAwfQ.abc123 */
			token?: string;
		};
		"models.LogsResponse": {
			containerName?: string;
			logs?: string;
		};
		"models.MemMetrics": {
			/** @description Available memory in bytes */
			availableMem?: number;
			/** @description This process's memory in MB */
			processMemMB?: number;
			/** @description This process's memory percentage */
			processMemPct?: number;
			/** @description Total physical memory in bytes */
			totalMem?: number;
			/** @description Memory usage percentage */
			usagePercent?: number;
			/** @description Used physical memory in bytes */
			usedMem?: number;
		};
		"models.Metrics": {
			/** @description CPU usage metrics */
			cpu?: components["schemas"]["models.CPUMetrics"];
			/** @description Disk usage metrics */
			disk?: components["schemas"]["models.DiskMetrics"];
			/** @description Memory usage metrics */
			mem?: components["schemas"]["models.MemMetrics"];
		};
		"models.MetricsResponse": {
			/** @description Detailed system metrics */
			metrics?: components["schemas"]["models.Metrics"];
			/** @description Basic server information */
			serverInfo?: components["schemas"]["models.ServerInfo"];
		};
		"models.NetemInterfaceInfo": {
			/** @description Percentage (might be missing in older clab versions) */
			corruption?: number;
			/** @description Duration string or empty */
			delay?: string;
			/** @description Interface name */
			interface?: string;
			/** @description Duration string or empty */
			jitter?: string;
			/** @description Percentage */
			packet_loss?: number;
			/** @description Kbit/s */
			rate?: number;
		};
		"models.NetemResetRequest": {
			/**
			 * @description Container/node name to reset impairments on (e.g., "clab-my-lab-srl1").
			 * @example clab-my-lab-srl1
			 */
			containerName: string;
			/**
			 * @description Interface name or interface alias to reset impairments on (e.g., "eth1" or "mgmt0").
			 * @example eth1
			 */
			interface: string;
		};
		"models.NetemSetRequest": {
			/**
			 * @description Container/node name to apply impairments on (e.g., "clab-my-lab-srl1").
			 * @example clab-my-lab-srl1
			 */
			containerName: string;
			/**
			 * @description Percentage (0.0 to 100.0)
			 * @example 0.1
			 */
			corruption?: number;
			/**
			 * @description Duration string (e.g., "100ms", "1s")
			 * @example 50ms
			 */
			delay?: string;
			/**
			 * @description Interface name or interface alias to apply impairments on (e.g., "eth1" or "mgmt0").
			 * @example eth1
			 */
			interface: string;
			/**
			 * @description Duration string, requires Delay
			 * @example 5ms
			 */
			jitter?: string;
			/**
			 * @description Percentage (0.0 to 100.0)
			 * @example 10.5
			 */
			loss?: number;
			/**
			 * @description Kbit/s (non-negative integer)
			 * @example 1000
			 */
			rate?: number;
		};
		"models.NetemShowResponse": {
			[key: string]: components["schemas"]["models.NetemInterfaceInfo"][];
		};
		"models.NodeInterfaceInfo": {
			interfaces?: components["schemas"]["models.InterfaceInfo"][];
			/** @description Name of the container node */
			name?: string;
		};
		"models.PasswordChangeRequest": {
			/** @description Required if not superuser */
			currentPassword?: string;
			newPassword: string;
		};
		"models.SSHAccessRequest": {
			/** @description How long the access should be valid for (e.g., "1h", "30m") */
			duration?: string;
			/** @description Optional override for container's SSH user */
			sshUsername?: string;
		};
		"models.SSHAccessResponse": {
			/** @description Example SSH command */
			command?: string;
			/** @description When this access expires */
			expiration?: string;
			/** @description API server's hostname or IP */
			host?: string;
			/** @description Allocated port on API server */
			port?: number;
			/** @description Username to use for SSH */
			username?: string;
		};
		"models.SSHSessionInfo": {
			/** @description When this access was created */
			created?: string;
			/** @description When this access expires */
			expiration?: string;
			/** @description Lab name */
			labName?: string;
			/** @description Node name */
			nodeName?: string;
			/** @description Allocated port on API server */
			port?: number;
			/** @description SSH username */
			username?: string;
		};
		"models.SaveConfigResponse": {
			/** @description Message indicating overall success. */
			message?: string;
			/** @description Detailed output from the 'clab save' command (often from stderr). */
			output?: string;
		};
		"models.ServerInfo": {
			/** @description When the server started */
			startTime?: string;
			/** @description Human-readable uptime */
			uptime?: string;
			/** @description API server version */
			version?: string;
		};
		"models.UserCreateRequest": {
			displayName?: string;
			groups?: string[];
			isSuperuser?: boolean;
			password: string;
			/** @description Default to /bin/bash if empty */
			shell?: string;
			username: string;
		};
		"models.UserDetails": {
			/** @description Full name from GECOS field */
			displayName?: string;
			gid?: string;
			groups?: string[];
			homeDir?: string;
			isApiUser?: boolean;
			isSuperuser?: boolean;
			shell?: string;
			uid?: string;
			username?: string;
		};
		"models.UserUpdateRequest": {
			displayName?: string;
			groups?: string[];
			isSuperuser?: boolean;
			shell?: string;
		};
		"models.VersionCheckResponse": {
			/**
			 * @description Raw output string from 'clab version check'.
			 * @example 🎉 A newer containerlab version (0.62.2) is available!
			 *     Release notes: https://containerlab.dev/rn/0.62/#0622
			 *     Run 'sudo clab version upgrade' or see https://containerlab.dev/install/ for installation options.
			 */
			checkResult?: string;
		};
		"models.VersionResponse": {
			/**
			 * @description Raw output string from 'clab version'.
			 * @example version: 0.50.0
			 *     commit: 1234abcd
			 *     date: 2024-01-15T10:00:00Z
			 *     github: https://github.com/srl-labs/containerlab
			 *     release notes: https://containerlab.dev/rn/0.50/
			 */
			versionInfo?: string;
		};
		"models.VethCreateRequest": {
			/**
			 * @description Endpoint A definition. Format: <node-name>:<interface-name> OR <kind>:<node-name>:<interface-name>
			 *     Example: "clab-demo-node1:eth1" or "bridge:br-1:br-eth1" or "host:veth-eth1"
			 * @example clab-demo-node1:eth1
			 */
			aEndpoint: string;
			/**
			 * @description Endpoint B definition. Format: <node-name>:<interface-name> OR <kind>:<node-name>:<interface-name>
			 *     Example: "clab-demo-node2:eth1" or "ovs-bridge:ovsbr-1:br-eth1"
			 * @example clab-demo-node2:eth1
			 */
			bEndpoint: string;
			/**
			 * @description MTU for the vEth pair. Defaults to 9500 if omitted.
			 * @example 1500
			 */
			mtu?: number;
		};
		"models.VxlanCreateRequest": {
			/**
			 * @description Optional: Linux device to use for the tunnel source. Auto-detected if omitted.
			 * @example eth0
			 */
			dev?: string;
			/**
			 * @description VxLAN Network Identifier (VNI). Defaults to 10 if omitted.
			 * @example 100
			 */
			id?: number;
			/**
			 * @description Name of the existing interface in the root namespace to bridge traffic with.
			 * @example srl_e1-1
			 */
			link: string;
			/**
			 * @description Optional: MTU for the VxLAN interface. Auto-calculated if omitted.
			 * @example 1400
			 */
			mtu?: number;
			/**
			 * @description UDP port number for the VxLAN tunnel. Defaults to 14789 if omitted.
			 * @example 4789
			 */
			port?: number;
			/**
			 * @description Remote VTEP IP address.
			 * @example 10.0.0.20
			 */
			remote: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
