#!/usr/bin/env bash
# =============================================================================
# vLab Deploy Script (Compose: Infra)
# Brings up Postgres, Redis, and RustFS (docker-compose.infra.yml) on a host
# reachable from the manager/worker hosts over Tailscale.
# =============================================================================

set -euo pipefail

REPO_RAW="https://raw.githubusercontent.com/nunu27/vlab-bun/main"
COMPOSE_URL="$REPO_RAW/docker-compose.infra.yml"
DEFAULT_SETUP_DIR="/opt/vlab/infra"

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GRN='\033[0;32m'
YLW='\033[1;33m'
BLU='\033[0;34m'
BLD='\033[1m'
RST='\033[0m'

info()    { echo -e "${BLU}${BLD}[*]${RST} $*"; }
success() { echo -e "${GRN}${BLD}[✓]${RST} $*"; }
warn()    { echo -e "${YLW}${BLD}[!]${RST} $*"; }
error()   { echo -e "${RED}${BLD}[✗]${RST} $*" >&2; }
die()     { error "$*"; exit 1; }

prompt() {
	local var="$1" label="$2" default="${3:-}"
	local answer=""
	if [[ -n "$default" ]]; then
		read -rp "  ${label} [${default}]: " answer
		answer="${answer:-$default}"
	else
		read -rp "  ${label}: " answer
	fi
	printf -v "$var" '%s' "$answer"
}

prompt_secret() {
	local var="$1" label="$2" default="${3:-}" min_len="${4:-0}"
	local answer=""
	while true; do
		if [[ -n "$default" ]]; then
			read -rsp "  ${label} [leave blank to keep existing]: " answer
			echo
			answer="${answer:-$default}"
		else
			read -rsp "  ${label}: " answer
			echo
		fi
		if [[ ${#answer} -lt $min_len ]]; then
			echo "  [!] ${label} must be at least ${min_len} characters long." >&2
		else
			break
		fi
	done
	printf -v "$var" '%s' "$answer"
}

gen_secret() {
	# Alphanumeric only: DB_PASSWORD ends up embedded in a postgres:// URI, and
	# unescaped URL-reserved characters (#, &, etc.) silently break it.
	LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom 2>/dev/null | head -c 32 || true
}

read_env() {
	local key="$1" file="$2"
	if [[ -f "$file" ]]; then
		grep -E "^${key}=" "$file" | head -1 | sed "s/^${key}=//" | tr -d '"' || true
	fi
}

echo
echo -e "${BLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RST}"
echo -e "${BLD}         vLab Compose: Infra Setup       ${RST}"
echo -e "${BLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RST}"
echo

prompt SETUP_DIR "Where should infra be set up?" "$DEFAULT_SETUP_DIR"

if [[ ! -d "$SETUP_DIR" ]]; then
	info "Creating directory $SETUP_DIR ..."
	sudo mkdir -p "$SETUP_DIR" || die "Failed to create $SETUP_DIR"
	sudo chown "$USER":"$USER" "$SETUP_DIR" || true
fi

cd "$SETUP_DIR"
success "Working directory: $(pwd)"

echo
info "Checking container runtime ..."
DOCKER_CMD="${DOCKER_CMD:-docker}"
COMPOSE_CMD="${COMPOSE_CMD:-$DOCKER_CMD compose}"
command -v "$DOCKER_CMD" &>/dev/null || die "$DOCKER_CMD is not installed."

echo
info "Checking Tailscale ..."
DETECTED_TAILSCALE_IP=""
if command -v tailscale &>/dev/null; then
	DETECTED_TAILSCALE_IP=$(tailscale ip -4 2>/dev/null || true)
fi
[[ -n "$DETECTED_TAILSCALE_IP" ]] || warn "Could not auto-detect a Tailscale IP; enter it manually."

ENV_FILE="$SETUP_DIR/.env.infra"

echo -e "\n${BLD}── Tailscale binding ────────────────────${RST}"
warn "Postgres/Redis/RustFS will publish ONLY on this address, never 0.0.0.0."
prompt TAILSCALE_IP "This host's Tailscale IP" "$(read_env TAILSCALE_IP "$ENV_FILE" || echo "${DETECTED_TAILSCALE_IP:-}")"
[[ -n "$TAILSCALE_IP" ]] || die "A Tailscale IP is required."

echo -e "\n${BLD}── Database (Postgres) ──────────────────${RST}"
prompt DB_USER "DB_USER" "$(read_env DB_USER "$ENV_FILE" || echo "vlab")"
prompt DB_NAME "DB_NAME" "$(read_env DB_NAME "$ENV_FILE" || echo "vlab")"
EXISTING_DB_PASSWORD="$(read_env DB_PASSWORD "$ENV_FILE")"
if [[ -z "$EXISTING_DB_PASSWORD" ]]; then
	DB_PASSWORD="$(gen_secret)"
	info "DB_PASSWORD auto-generated."
else
	prompt_secret DB_PASSWORD "DB_PASSWORD" "$EXISTING_DB_PASSWORD"
fi

echo -e "\n${BLD}── S3 / RustFS ──────────────────────────${RST}"
prompt RUSTFS_ACCESS_KEY "RUSTFS_ACCESS_KEY" "$(read_env RUSTFS_ACCESS_KEY "$ENV_FILE" || echo "vlabadmin")"
EXISTING_RUSTFS_SECRET_KEY="$(read_env RUSTFS_SECRET_KEY "$ENV_FILE")"
if [[ -z "$EXISTING_RUSTFS_SECRET_KEY" ]]; then
	RUSTFS_SECRET_KEY="$(gen_secret)"
	info "RUSTFS_SECRET_KEY auto-generated."
else
	prompt_secret RUSTFS_SECRET_KEY "RUSTFS_SECRET_KEY" "$EXISTING_RUSTFS_SECRET_KEY" 8
fi

info "Writing .env.infra ..."
cat > "$ENV_FILE" <<EOF
# Generated by vLab deploy script on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
TAILSCALE_IP=${TAILSCALE_IP}

DB_USER=${DB_USER}
DB_NAME=${DB_NAME}
DB_PASSWORD=${DB_PASSWORD}
POSTGRES_PASSWORD=${DB_PASSWORD}

RUSTFS_ACCESS_KEY=${RUSTFS_ACCESS_KEY}
RUSTFS_SECRET_KEY=${RUSTFS_SECRET_KEY}
EOF
chmod 600 "$ENV_FILE"
success ".env.infra written."

echo
info "Fetching latest docker-compose.infra.yml ..."
curl -fsSL "$COMPOSE_URL" -o "$SETUP_DIR/docker-compose.infra.yml" \
	|| die "Failed to download docker-compose.infra.yml from $COMPOSE_URL"
success "docker-compose.infra.yml updated."

echo
info "Starting infra services ..."
$COMPOSE_CMD -f docker-compose.infra.yml --env-file .env.infra up -d
success "Infra services started."

echo
info "Initializing RustFS 'vlab' bucket ..."
if MC_OUTPUT=$($DOCKER_CMD run --rm --network host --entrypoint sh minio/mc -c \
	"mc alias set rustfs http://${TAILSCALE_IP}:9000 ${RUSTFS_ACCESS_KEY} ${RUSTFS_SECRET_KEY} && mc mb --ignore-existing rustfs/vlab" 2>&1); then
	success "RustFS bucket 'vlab' is ready."
else
	warn "Failed to automatically create the RustFS bucket. Create it manually via the console on port 9001."
	echo "$MC_OUTPUT"
fi

echo
echo -e "${GRN}${BLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RST}"
echo -e "${GRN}${BLD}  vLab infra is deployed!${RST}"
echo -e "${GRN}${BLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RST}"
echo
info "Paste these into .env.manager on every manager host:"
echo "  DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${TAILSCALE_IP}:5432/${DB_NAME}"
echo "  REDIS_URL=redis://${TAILSCALE_IP}:6379"
echo "  S3_ENDPOINT=http://${TAILSCALE_IP}:9000/vlab"
echo "  S3_ACCESS_KEY=${RUSTFS_ACCESS_KEY}"
echo "  S3_SECRET_KEY=${RUSTFS_SECRET_KEY}"
echo
info "Useful commands:"
echo "  View logs:    docker compose -f $SETUP_DIR/docker-compose.infra.yml logs -f"
echo "  Status:       docker compose -f $SETUP_DIR/docker-compose.infra.yml ps"
echo "  Stop:         docker compose -f $SETUP_DIR/docker-compose.infra.yml down"
echo
